const STATUS = {
    NONE: "NONE",
    FAILED: "FAILED",
    RUNNING: "RUNNING",
    PASSED: "PASSED",
    SKIPPED: "SKIPPED"
}
const ERRORCODE = {
    UNEXPECTED_RESPONSE_CODE: "000",
    INVALID_JSON: "001",
    RESPONSE_ERROR: "002",
    LOGIC_ERROR: "003",
    BAD_REQUEST: "400",
    UNAUTHORIZED_ACCESS: "401",
    FORBIDDED: "403",
    RESOURCE_NOT_FOUND: "404",
    METHOD_NOT_ALLOWED: "405",
    NOT_ACCEPTABLE: "405",
    REQUEST_TIMEOUT: "408",
    UNPROCESSABLE_ENTITY: "422",
    INTERNAL_SERVER_ERROR: "500",
    NOT_IMPLEMENTED: "501",
    BAD_GATEWAY: "502"
}