addGlobalHeader('Connection','keep-alive');
//addGlobalHeader('Accept-Encoding','gzip');
addGlobalHeader('User-Agent','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36');

var page = open('https://demosite.appvance.com:443/');
  var htmlResp= page.resp;
  var htmlExtract = extractHTML(htmlResp);
  var $corr1= htmlExtract.getAttrByXPath('//html/head/link[1]/@href');
  $corr1 = baseURL($corr1);
  var $corr2= htmlExtract.getAttrByXPath('//html/head/link[3]/@href');
  var $corr3= htmlExtract.getAttrByXPath("//div[@id='product_1']/div[1]/div[1]/a[1]/@href");
  var $corr4= htmlExtract.getAttrByXPath("//div[@id='product_1']/div[1]/div[1]/a/img[1]/@src");
  var $corr5= htmlExtract.getAttrByXPath("//div[@id='main-nav-bar']/ul/li[1]/noscript/a[1]/@href");
  var resp= page.get("//div[@id='product_1']/div[1]/div[1]/a/img[1]");
  var $corr7= resp.getHeader('ETag');
  var resp= page.get('//html/head/link[3]');
  var $corr6= resp.getHeader('ETag');
var resp = get($corr1+'/cart_link');
  var $corr8= resp.getHeader('ETag');
get($corr1+$corr2);
get($corr1+'/assets/bootstrap/glyphicons-halflings-regular-fe185d11a49676890d47bb783312a0cda5a44c4039214094e7957b4c040ef11c.woff2');
var page = open($corr1+$corr3);
  var htmlResp= page.resp;
  var htmlExtract = extractHTML(htmlResp);
  var $corr9= htmlExtract.getAttrByXPath('//html/head/meta[7]/@content');
get($corr1+'/cart_link');
var form = formData();
  form.put('utf8','✓');
  form.put('authenticity_token',$corr9);
  form.put('variant_id','1');
  form.put('quantity','1');
  form.put('button','');
var data = 'utf8=%E2%9C%93&authenticity_token=6nziiX9iT3JNzarugSMTuphpEKX8TNsxnUB1CBCKX6SXG27rdHIRFRfmlW14h6x3xPy1TDDMhCp%2Fik5T3GAEow%3D%3D&variant_id=1&quantity=1&button=';
post($corr1+'/orders/populate', data, "application/x-www-form-urlencoded");
var page = open($corr1+'/cart?variant_id=1&');
  var htmlResp= page.resp;
  var htmlExtract = extractHTML(htmlResp);
  var $corr10= htmlExtract.getAttrByXPath('//html/head/meta[7]/@content');
  var $corr11= htmlExtract.getAttrByXPath("//div[@id='content']/div[1]/div[1]/form/div[1]/div[1]/table/tbody/input[1][@id='order_line_items_attributes_0_id']/@value");
var resp = get($corr1+'/cart_link');
  var $corr12= resp.getHeader('ETag');
get($corr1+$corr4);
var form = formData();
  form.put('utf8','✓');
  form.put('_method','patch');
  form.put('authenticity_token',$corr10);
  form.put('order[line_items_attributes][0][quantity]','1');
  form.put('order[line_items_attributes][0][id]',$corr11);
  form.put('order[coupon_code]','');
var data = 'utf8=%E2%9C%93&_method=patch&authenticity_token=juHIHmBcvrC8f66wAhuXcrqMuD8m3Ca6RML7RDzd%2FpDzhkR8a0zg1%2BZUkTP7vyi%2F5hkd1upceaGmCMAf8Dellw%3D%3D&order%5Bline_items_attributes%5D%5B0%5D%5Bquantity%5D=1&order%5Bline_items_attributes%5D%5B0%5D%5Bid%5D=63580&order%5Bcoupon_code%5D=';
post($corr1+$corr5, data, "application/x-www-form-urlencoded");
var page = open($corr1+$corr5);
  var htmlResp= page.resp;
  var htmlExtract = extractHTML(htmlResp);
  var $corr13= htmlExtract.getAttrByXPath('//html/head/meta[7]/@content');
var resp = get($corr1+'/cart_link');
  var $corr14= resp.getHeader('ETag');
var form = formData();
  form.put('utf8','✓');
  form.put('_method','patch');
  form.put('authenticity_token',$corr13);
  form.put('order[line_items_attributes][0][quantity]','1');
  form.put('order[line_items_attributes][0][id]',$corr11);
  form.put('checkout','');
  form.put('order[coupon_code]','');
var data = 'utf8=%E2%9C%93&_method=patch&authenticity_token=3OCswCCcmjusMjh%2Fr%2BzqI3h78xe2evlQCChROxDK9c%2BhhyCiK4zEXPYZB%2FxWSFXuJO5W%2Fnr6pkvq4mpg3CCuyA%3D%3D&order%5Bline_items_attributes%5D%5B0%5D%5Bquantity%5D=1&order%5Bline_items_attributes%5D%5B0%5D%5Bid%5D=63580&checkout=&order%5Bcoupon_code%5D=';
post($corr1+$corr5, data, "application/x-www-form-urlencoded");
get($corr1+'/checkout/address');
var page = open($corr1+'/checkout/registration');
  var htmlResp= page.resp;
  var htmlExtract = extractHTML(htmlResp);
  var $corr15= htmlExtract.getAttrByXPath('//html/head/meta[7]/@content');
  var $corr16= htmlExtract.getAttrByXPath("//div[@id='guest_checkout']/form/p/input[1]/@value");
var resp = get($corr1+'/cart_link');
  var $corr17= resp.getHeader('ETag');
var form = formData();
  form.put('utf8','✓');
  form.put('_method','put');
  form.put('authenticity_token',$corr15);
  form.put('order[email]','n@appvance.com');
  form.put('commit',$corr16);
var data = 'utf8=%E2%9C%93&_method=put&authenticity_token=TwLGo7O5O%2FC9lp%2BiToMNsnDZS4pFXBtHQ6e0LVS%2FXJgyZUrBuKlll%2Be9oCG3J7J%2FLEzuY4ncRFyhbY92mFUHnw%3D%3D&order%5Bemail%5D=n%40appvance.com&commit=Continue';
post($corr1+'/checkout/registration', data, "application/x-www-form-urlencoded");
open($corr1+'/checkout');
get($corr1+'/cart_link');
get($corr1+'/api/v1/states?country_id=232&');
