processScript("{ds}/setup.js","js");
setVariablesIfNeeded('{ds}/dpl.csv', 'HashDPL', 0);
addSmartTagsLibrary("{ds}/Test1.stags");
addValidationsWorkbench("{ds}/Test1.valid");
setFailOnValidations(true);
prepareDomain($baseURL);
setFindOnlyVisible(true);
setFindOnlyEnabled(true);
selectMainFrame();
navigateTo($baseURL);
click(LeftMenu('Spree'));
click(LeftMenu('Spree'));
click(HomeButton('Home'));
click(Products('Ruby on Rails Baseball Jersey'));
click(HomeButton('Home'));
click(LeftMenu('Ruby'));
click(Products('Ruby Baseball Jersey'));
click(HomeButton('Home'));
click(Products('Ruby on Rails Baseball Jersey'));
click(HomeButton('Home'));
click(LeftMenu('Clothing'));
click(Products('Ruby on Rails Baseball Jersey'));
click(HomeButton('Home'));
click(Products('Ruby on Rails Baseball Jersey'));
click(AddToCart('add-to-cart-button'));
click(HomeButton('Home'));
click(LeftMenu('Ruby'));
click(LeftMenu('Bags'));
click(LeftMenu('Spree'));
click(HomeButton('Home'));
click(Products('Ruby on Rails Jr. Spaghetti'));
click(HomeButton('Home'));
click(LeftMenu('Mugs'));
click(LeftMenu('Rails'));
click(LeftMenu('Spree'));
click(LeftMenu('Spree'));
click(HomeButton('Home'));
click(Products('Ruby on Rails Ringer T-Shirt'));
click(HomeButton('Home'));
click(LeftMenu('Rails'));
click(LeftMenu('Clothing'));
click(LeftMenu('Spree'));
click(LeftMenu('Clothing'));
click(LeftMenu('Ruby'));
click(LeftMenu('Bags'));
click(LeftMenu('Clothing'));
click(LeftMenu('Mugs'));
click(LeftMenu('Spree'));
click(LeftMenu('Spree'));
